### PR TITLE
Updates in documentation for APK 2.0.0

### PR DESCRIPTION
**Pull request by nancyespinoza**
New index tree:
6.	Settings
7.	Generic Features
7.1	Login
7.2	Account Recovery
7.3	Blocking session (PIN)
7.4	Instructions/ information buttons
7.5	Filter
7.6	Sync Information
7.6.1	Granular Sync
7.6.2	SMS Sync
7.7	Org unit
7.8	Data Sets
7.9	Differentiating tracker and event programs
7.10	Sharing Data
7.11	Capture Coordinates
7.11.1	TEI coordinates
7.11.2	Polygons
7.12	Capture images
7.13	Show in Map
8.	Programs Specific features
8.1	Program with registration
8.1.1	Complete/Re-open event
8.1.2	Complete/Deactivate Enrollment
8.1.3	Reset Search Fields
8.1.4	Search screen for all Tracked Entity Type
8.1.5	TEI Dashboard across programs
8.1.6	TEI enrollment history and new enrollment
8.1.7	Delete TEI’s & Enrollments
8.2	Program without registration
8.2.1	 Complete event and Field completion percentage
9.	Features supported
9.1	Data Sets features
9.2	Program features
9.3	Program stage features
9.4	Program with registration: Tracked entity dashboard features
9.5	Program without registration: Single event program specific features
10.	Program rules supported in Android Capture App
10.1	Program rule Variable source types supported
10.2	Program rule Actions supported (Data element in current event)
10.3	Program rule Actions supported (Other variables)
10.4	Functions to use in program rule expressions
10.5	Standard variables to use in program rule expressions
11.	Program Indicators
11.1	Variables to use in a program indicator expression or filter
12. Value types supported

### CODE REVIEW

**Comment by jaboto** [comment]
Hey @nancyespinoza it looks good at to me but was just wondering, have you tried building the doc? Probably it would be easier to review it that way... I think that for future modifications we can start working on a branch that the rest of the team can pull, build and then merge that branch into master. What do you think @mmvila, @Balcan and @josemp10 ?

**Comment by Balcan** [comment]
> Hey @nancyespinoza it looks good at to me but was just wondering, have you tried building the doc? Probably it would be easier to review it that way... I think that for future modifications we can start working on a branch that the rest of the team can pull, build and then merge that branch into master. What do you think @mmvila, @Balcan and @josemp10 ?

Yes, it will be easier for us if @nancyespinoza works directly in the repository. This way we can fix some problems (like the one this PR is having now with Bitrise)

**Comment by mmvila** [comment]
Hi @Balcan , @jaboto ,   @nancyespinoza  and I had a call and went through the documentation on her screen and I asked her to send the pull request.  I was not expecting to "break" the build with the documentation... Let's discuss tomorrow in the meeting.

**Comment by jaboto** [comment]
A quick comment. While including full-screen screenshots I think it would be nicer to remove some parts of the screen:
image

**Pull request merged**
