### PR TITLE
feat: [ANDROAPP-3760] Add matomo trackers

### PR DESCRIPTION
**Pull request by JaimeToca**
## Description
Please include a summary of the change and include the related jira issue if it exists.

[ jira issue ](https://jira.dhis2.org/browse/

## Solution description
If this PR is a fix include a brief description on how the issue is solved.
## Covered unit test cases
Describe the tests that you ran to verify your changes.
## Where did you test this issue?
- [ ] Smartphone Emulator
- [ ] Tablet Emulator
- [ ] Smartphone
- [ ] Tablet
## Which Android versions did you test this issue?
- [ ] 4.4
- [ ] 5.X - 6.X
- [ ] 7.X
- [ ] 8.X
- [ ] 9.X - 10.X
- [ ] Other
## Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by Balcan — APPROVED** [review]
My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.

**Review by ferdyrod — APPROVED** [review]

**Comment by JaimeToca** [comment]
> My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.

Sounds good @Balcan , do you think is it better to have a analytics constant class per presenter instead ?

**Comment by Balcan** [comment]
> > My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.
> 
> Sounds good @Balcan , do you think is it better to have a analytics constant class per presenter instead ? Or just one?

O would have just one class. We can discuss this later in the daily. I was thinking on having different access layers

> > My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.
> 
> Sounds good @Balcan , do you think is it better to have a analytics constant class per presenter instead ? Or just one?

We can discuss it later in the daily. But I was thinking on having some kind of provider so that we can group the constants by screen, category and action and use them like:
`Analytics.Screen.Home, Analytics.Category.SyncButton, Analytics.Action.Click`

**Comment by JaimeToca** [comment]
> > > My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.
> > 
> > 
> > Sounds good @Balcan , do you think is it better to have a analytics constant class per presenter instead ? Or just one?
> 
> O would have just one class. We can discuss this later in the daily. I was thinking on having different access layers
> 
> > > My only comment. Wouldn't it be better if we move all tracking constants to a single class file? This way we can avoid duplications or name changes between screens.
> > 
> > 
> > Sounds good @Balcan , do you think is it better to have a analytics constant class per presenter instead ? Or just one?
> 
> We can discuss it later in the daily. But I was thinking on having some kind of provider so that we can group the constants by screen, category and action and use them like:
> `Analytics.Screen.Home, Analytics.Category.SyncButton, Analytics.Action.Click`

Sounds good :+1: lets talk about it in the daily

**Pull request merged**
